export interface StockMeta {
  ticker: string;
  name: string;
  market: 'US' | 'UK';
  sector: string;
  trading212: boolean;
}

export const US_STOCKS: StockMeta[] = [
  // Tech - Mega Cap
  { ticker: 'AAPL', name: 'Apple', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'MSFT', name: 'Microsoft', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'GOOGL', name: 'Alphabet', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'AMZN', name: 'Amazon', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'NVDA', name: 'NVIDIA', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'META', name: 'Meta Platforms', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'TSLA', name: 'Tesla', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'AVGO', name: 'Broadcom', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'ORCL', name: 'Oracle', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'CRM', name: 'Salesforce', market: 'US', sector: 'Technology', trading212: true },
  // Tech - Growth
  { ticker: 'AMD', name: 'AMD', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'INTC', name: 'Intel', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'NFLX', name: 'Netflix', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'ADBE', name: 'Adobe', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'CSCO', name: 'Cisco', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'QCOM', name: 'Qualcomm', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'INTU', name: 'Intuit', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'AMAT', name: 'Applied Materials', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'PANW', name: 'Palo Alto Networks', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'SNPS', name: 'Synopsys', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'NOW', name: 'ServiceNow', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'UBER', name: 'Uber', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'SHOP', name: 'Shopify', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'SNOW', name: 'Snowflake', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'PLTR', name: 'Palantir', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'NET', name: 'Cloudflare', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'CRWD', name: 'CrowdStrike', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'DDOG', name: 'Datadog', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'MDB', name: 'MongoDB', market: 'US', sector: 'Technology', trading212: true },
  // Financials
  { ticker: 'JPM', name: 'JPMorgan Chase', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'BAC', name: 'Bank of America', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'WFC', name: 'Wells Fargo', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'GS', name: 'Goldman Sachs', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'MS', name: 'Morgan Stanley', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'V', name: 'Visa', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'MA', name: 'Mastercard', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'AXP', name: 'American Express', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'BLK', name: 'BlackRock', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'SCHW', name: 'Charles Schwab', market: 'US', sector: 'Financials', trading212: true },
  // Healthcare
  { ticker: 'JNJ', name: 'Johnson & Johnson', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'UNH', name: 'UnitedHealth', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'PFE', name: 'Pfizer', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'ABBV', name: 'AbbVie', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'MRK', name: 'Merck', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'LLY', name: 'Eli Lilly', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'TMO', name: 'Thermo Fisher', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'ABT', name: 'Abbott Labs', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'AMGN', name: 'Amgen', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'GILD', name: 'Gilead Sciences', market: 'US', sector: 'Healthcare', trading212: true },
  // Consumer
  { ticker: 'WMT', name: 'Walmart', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'PG', name: 'Procter & Gamble', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'KO', name: 'Coca-Cola', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'PEP', name: 'PepsiCo', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'COST', name: 'Costco', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'MCD', name: "McDonald's", market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'NKE', name: 'Nike', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'SBUX', name: 'Starbucks', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'HD', name: 'Home Depot', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'LOW', name: "Lowe's", market: 'US', sector: 'Consumer Cyclical', trading212: true },
  // Energy
  { ticker: 'XOM', name: 'ExxonMobil', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'CVX', name: 'Chevron', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'COP', name: 'ConocoPhillips', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'SLB', name: 'Schlumberger', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'EOG', name: 'EOG Resources', market: 'US', sector: 'Energy', trading212: true },
  // Industrials
  { ticker: 'CAT', name: 'Caterpillar', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'BA', name: 'Boeing', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'HON', name: 'Honeywell', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'UPS', name: 'UPS', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'RTX', name: 'RTX Corp', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'DE', name: 'Deere & Co', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'GE', name: 'GE Aerospace', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'LMT', name: 'Lockheed Martin', market: 'US', sector: 'Industrials', trading212: true },
  // Communication
  { ticker: 'DIS', name: 'Disney', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'CMCSA', name: 'Comcast', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'T', name: 'AT&T', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'VZ', name: 'Verizon', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'TMUS', name: 'T-Mobile', market: 'US', sector: 'Communication', trading212: true },
  // Real Estate / Utilities
  { ticker: 'AMT', name: 'American Tower', market: 'US', sector: 'Real Estate', trading212: true },
  { ticker: 'PLD', name: 'Prologis', market: 'US', sector: 'Real Estate', trading212: true },
  { ticker: 'NEE', name: 'NextEra Energy', market: 'US', sector: 'Utilities', trading212: true },
  { ticker: 'DUK', name: 'Duke Energy', market: 'US', sector: 'Utilities', trading212: true },
  // Russell 2000 / Small-Mid growth
  { ticker: 'SOFI', name: 'SoFi Technologies', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'RIVN', name: 'Rivian', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'LCID', name: 'Lucid Group', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'COIN', name: 'Coinbase', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'RBLX', name: 'Roblox', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'U', name: 'Unity Software', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'AFRM', name: 'Affirm', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'HOOD', name: 'Robinhood', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'PATH', name: 'UiPath', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'PINS', name: 'Pinterest', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'SNAP', name: 'Snap', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'TTD', name: 'Trade Desk', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'ROKU', name: 'Roku', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'ZS', name: 'Zscaler', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'BILL', name: 'Bill Holdings', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'HUBS', name: 'HubSpot', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'SMCI', name: 'Super Micro', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'ARM', name: 'Arm Holdings', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'AI', name: 'C3.ai', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'CELH', name: 'Celsius Holdings', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'MARA', name: 'Marathon Digital', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'APLD', name: 'Applied Digital', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'HIMS', name: 'Hims & Hers Health', market: 'US', sector: 'Healthcare', trading212: true },
  // Materials
  { ticker: 'LIN', name: 'Linde', market: 'US', sector: 'Materials', trading212: true },
  { ticker: 'APD', name: 'Air Products', market: 'US', sector: 'Materials', trading212: true },
  { ticker: 'FCX', name: 'Freeport-McMoRan', market: 'US', sector: 'Materials', trading212: true },
  { ticker: 'NEM', name: 'Newmont', market: 'US', sector: 'Materials', trading212: true },
  // Biotech
  { ticker: 'MRNA', name: 'Moderna', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'REGN', name: 'Regeneron', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'VRTX', name: 'Vertex Pharma', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'ISRG', name: 'Intuitive Surgical', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'DXCM', name: 'DexCom', market: 'US', sector: 'Healthcare', trading212: true },
  // More S&P 500
  { ticker: 'BRK-B', name: 'Berkshire Hathaway', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'SPGI', name: 'S&P Global', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'MMM', name: '3M', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'IBM', name: 'IBM', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'GEV', name: 'GE Vernova', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'ABNB', name: 'Airbnb', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'GM', name: 'General Motors', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'F', name: 'Ford Motor', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'PYPL', name: 'PayPal', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'BKNG', name: 'Booking Holdings', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'TXN', name: 'Texas Instruments', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'MU', name: 'Micron', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'LRCX', name: 'Lam Research', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'KLAC', name: 'KLA Corp', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'ADI', name: 'Analog Devices', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'MRVL', name: 'Marvell Technology', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'ON', name: 'ON Semiconductor', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'FTNT', name: 'Fortinet', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'WDAY', name: 'Workday', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'TEAM', name: 'Atlassian', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'VEEV', name: 'Veeva Systems', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'ZM', name: 'Zoom Video', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'OKTA', name: 'Okta', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'DASH', name: 'DoorDash', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'SPOT', name: 'Spotify', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'SE', name: 'Sea Limited', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'MELI', name: 'MercadoLibre', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'NU', name: 'Nu Holdings', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'GRAB', name: 'Grab Holdings', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'CPNG', name: 'Coupang', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  // ── S&P 500 — Financials (missing) ──
  { ticker: 'C', name: 'Citigroup', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'COF', name: 'Capital One', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'PNC', name: 'PNC Financial', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'USB', name: 'U.S. Bancorp', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'TFC', name: 'Truist Financial', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'STT', name: 'State Street', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'BK', name: 'Bank of New York Mellon', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'ICE', name: 'Intercontinental Exchange', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'CME', name: 'CME Group', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'MCO', name: 'Moody\'s', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'MSCI', name: 'MSCI', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'FISV', name: 'Fiserv', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'BX', name: 'Blackstone', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'KKR', name: 'KKR & Co', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'APO', name: 'Apollo Global Management', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'PGR', name: 'Progressive', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'CB', name: 'Chubb', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'MET', name: 'MetLife', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'AFL', name: 'Aflac', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'TRV', name: 'Travelers', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'ALL', name: 'Allstate', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'AON', name: 'Aon', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'FICO', name: 'Fair Isaac (FICO)', market: 'US', sector: 'Technology', trading212: true },
  // ── S&P 500 — Technology (missing) ──
  { ticker: 'ACN', name: 'Accenture', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'CDNS', name: 'Cadence Design Systems', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'ANET', name: 'Arista Networks', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'DELL', name: 'Dell Technologies', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'HPE', name: 'Hewlett Packard Enterprise', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'HPQ', name: 'HP Inc', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'APH', name: 'Amphenol', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'MSI', name: 'Motorola Solutions', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'ADSK', name: 'Autodesk', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'CTSH', name: 'Cognizant', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'NXPI', name: 'NXP Semiconductors', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'MCHP', name: 'Microchip Technology', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'MPWR', name: 'Monolithic Power Systems', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'ADP', name: 'Automatic Data Processing', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'ASML', name: 'ASML Holding', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'TSM', name: 'Taiwan Semiconductor', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'APP', name: 'AppLovin', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'AXON', name: 'Axon Enterprise', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'EFX', name: 'Equifax', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'MSTR', name: 'MicroStrategy', market: 'US', sector: 'Technology', trading212: true },
  // ── S&P 500 — Healthcare (missing) ──
  { ticker: 'DHR', name: 'Danaher', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'SYK', name: 'Stryker', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'BSX', name: 'Boston Scientific', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'MDT', name: 'Medtronic', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'EW', name: 'Edwards Lifesciences', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'IDXX', name: 'IDEXX Laboratories', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'HCA', name: 'HCA Healthcare', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'ELV', name: 'Elevance Health', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'CI', name: 'Cigna Group', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'CVS', name: 'CVS Health', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'MCK', name: 'McKesson', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'BMY', name: 'Bristol-Myers Squibb', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'BIIB', name: 'Biogen', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'GEHC', name: 'GE HealthCare', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'ZTS', name: 'Zoetis', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'A', name: 'Agilent Technologies', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'BDX', name: 'Becton Dickinson', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'ALNY', name: 'Alnylam Pharmaceuticals', market: 'US', sector: 'Healthcare', trading212: true },
  // ── S&P 500 — Industrials (missing) ──
  { ticker: 'ETN', name: 'Eaton', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'EMR', name: 'Emerson Electric', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'PH', name: 'Parker-Hannifin', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'ITW', name: 'Illinois Tool Works', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'GD', name: 'General Dynamics', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'NOC', name: 'Northrop Grumman', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'TDG', name: 'TransDigm', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'WM', name: 'Waste Management', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'CTAS', name: 'Cintas', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'URI', name: 'United Rentals', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'UNP', name: 'Union Pacific', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'NSC', name: 'Norfolk Southern', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'FDX', name: 'FedEx', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'DAL', name: 'Delta Air Lines', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'UAL', name: 'United Airlines', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'LUV', name: 'Southwest Airlines', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'PCAR', name: 'PACCAR', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'ODFL', name: 'Old Dominion Freight', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'FAST', name: 'Fastenal', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'PWR', name: 'Quanta Services', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'TT', name: 'Trane Technologies', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'CARR', name: 'Carrier Global', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'CSX', name: 'CSX', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'CPRT', name: 'Copart', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'RKLB', name: 'Rocket Lab', market: 'US', sector: 'Industrials', trading212: true },
  // ── S&P 500 — Consumer Cyclical (missing) ──
  { ticker: 'TJX', name: 'TJX Companies', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'CMG', name: 'Chipotle Mexican Grill', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'LULU', name: 'Lululemon', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'ORLY', name: "O'Reilly Automotive", market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'DHI', name: 'D.R. Horton', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'LEN', name: 'Lennar', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'HLT', name: 'Hilton', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'MAR', name: 'Marriott', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'YUM', name: 'Yum! Brands', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'ROST', name: 'Ross Stores', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'DECK', name: 'Deckers Outdoor', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'CCL', name: 'Carnival', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'RCL', name: 'Royal Caribbean', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'CVNA', name: 'Carvana', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'EBAY', name: 'eBay', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'EXPE', name: 'Expedia', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'APTV', name: 'Aptiv', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  // ── S&P 500 — Consumer Defensive (missing) ──
  { ticker: 'PM', name: 'Philip Morris', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'MO', name: 'Altria Group', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'CL', name: 'Colgate-Palmolive', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'MDLZ', name: 'Mondelez', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'TGT', name: 'Target', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'KR', name: 'Kroger', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'SYY', name: 'Sysco', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'MNST', name: 'Monster Beverage', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'KDP', name: 'Keurig Dr Pepper', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'GIS', name: 'General Mills', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'KHC', name: 'Kraft Heinz', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'HSY', name: 'Hershey', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'ADM', name: 'Archer-Daniels-Midland', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'STZ', name: 'Constellation Brands', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'DG', name: 'Dollar General', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'DLTR', name: 'Dollar Tree', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'KMB', name: 'Kimberly-Clark', market: 'US', sector: 'Consumer Defensive', trading212: true },
  // ── S&P 500 — Energy (missing) ──
  { ticker: 'PSX', name: 'Phillips 66', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'VLO', name: 'Valero Energy', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'MPC', name: 'Marathon Petroleum', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'OXY', name: 'Occidental Petroleum', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'DVN', name: 'Devon Energy', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'FANG', name: 'Diamondback Energy', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'HAL', name: 'Halliburton', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'BKR', name: 'Baker Hughes', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'KMI', name: 'Kinder Morgan', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'WMB', name: 'Williams Companies', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'OKE', name: 'ONEOK', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'FSLR', name: 'First Solar', market: 'US', sector: 'Energy', trading212: true },
  // ── S&P 500 — Utilities (missing) ──
  { ticker: 'SO', name: 'Southern Co', market: 'US', sector: 'Utilities', trading212: true },
  { ticker: 'D', name: 'Dominion Energy', market: 'US', sector: 'Utilities', trading212: true },
  { ticker: 'EXC', name: 'Exelon', market: 'US', sector: 'Utilities', trading212: true },
  { ticker: 'SRE', name: 'Sempra Energy', market: 'US', sector: 'Utilities', trading212: true },
  { ticker: 'AEP', name: 'American Electric Power', market: 'US', sector: 'Utilities', trading212: true },
  { ticker: 'PCG', name: 'PG&E', market: 'US', sector: 'Utilities', trading212: true },
  { ticker: 'CEG', name: 'Constellation Energy', market: 'US', sector: 'Utilities', trading212: true },
  { ticker: 'VST', name: 'Vistra', market: 'US', sector: 'Utilities', trading212: true },
  { ticker: 'AWK', name: 'American Water Works', market: 'US', sector: 'Utilities', trading212: true },
  { ticker: 'ED', name: 'Consolidated Edison', market: 'US', sector: 'Utilities', trading212: true },
  // ── S&P 500 — Materials (missing) ──
  { ticker: 'SHW', name: 'Sherwin-Williams', market: 'US', sector: 'Materials', trading212: true },
  { ticker: 'ECL', name: 'Ecolab', market: 'US', sector: 'Materials', trading212: true },
  { ticker: 'DOW', name: 'Dow Inc', market: 'US', sector: 'Materials', trading212: true },
  { ticker: 'DD', name: 'DuPont', market: 'US', sector: 'Materials', trading212: true },
  { ticker: 'NUE', name: 'Nucor', market: 'US', sector: 'Materials', trading212: true },
  { ticker: 'VMC', name: 'Vulcan Materials', market: 'US', sector: 'Materials', trading212: true },
  { ticker: 'ALB', name: 'Albemarle', market: 'US', sector: 'Materials', trading212: true },
  { ticker: 'CTVA', name: 'Corteva', market: 'US', sector: 'Materials', trading212: true },
  { ticker: 'BALL', name: 'Ball Corp', market: 'US', sector: 'Materials', trading212: true },
  // ── S&P 500 — Real Estate (missing) ──
  { ticker: 'EQIX', name: 'Equinix', market: 'US', sector: 'Real Estate', trading212: true },
  { ticker: 'DLR', name: 'Digital Realty', market: 'US', sector: 'Real Estate', trading212: true },
  { ticker: 'SPG', name: 'Simon Property Group', market: 'US', sector: 'Real Estate', trading212: true },
  { ticker: 'CCI', name: 'Crown Castle', market: 'US', sector: 'Real Estate', trading212: true },
  { ticker: 'PSA', name: 'Public Storage', market: 'US', sector: 'Real Estate', trading212: true },
  { ticker: 'O', name: 'Realty Income', market: 'US', sector: 'Real Estate', trading212: true },
  { ticker: 'WELL', name: 'Welltower', market: 'US', sector: 'Real Estate', trading212: true },
  { ticker: 'VICI', name: 'VICI Properties', market: 'US', sector: 'Real Estate', trading212: true },
  { ticker: 'IRM', name: 'Iron Mountain', market: 'US', sector: 'Real Estate', trading212: true },
  { ticker: 'CBRE', name: 'CBRE Group', market: 'US', sector: 'Real Estate', trading212: true },
  // ── S&P 500 — Communication (missing) ──
  { ticker: 'CHTR', name: 'Charter Communications', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'EA', name: 'Electronic Arts', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'TTWO', name: 'Take-Two Interactive', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'LYV', name: 'Live Nation', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'WBD', name: 'Warner Bros Discovery', market: 'US', sector: 'Communication', trading212: true },
  // ── Trending / Retail Favourites ──
  { ticker: 'GME', name: 'GameStop', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'AMC', name: 'AMC Entertainment', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'BABA', name: 'Alibaba', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'PDD', name: 'PDD Holdings (Temu)', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'NIO', name: 'NIO', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'XPEV', name: 'XPeng', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'LI', name: 'Li Auto', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'BIDU', name: 'Baidu', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'RIOT', name: 'Riot Platforms', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'IONQ', name: 'IonQ', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'RGTI', name: 'Rigetti Computing', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'SOUN', name: 'SoundHound AI', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'UPST', name: 'Upstart', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'LYFT', name: 'Lyft', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'JOBY', name: 'Joby Aviation', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'LUNR', name: 'Intuitive Machines', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'ASTS', name: 'AST SpaceMobile', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'WOLF', name: 'Wolfspeed', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'QS', name: 'QuantumScape', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'DJT', name: 'Trump Media', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'GPN', name: 'Global Payments', market: 'US', sector: 'Fintech', trading212: true },
];

export const UK_STOCKS: StockMeta[] = [
  // FTSE 100
  { ticker: 'SHEL.L', name: 'Shell', market: 'UK', sector: 'Energy', trading212: true },
  { ticker: 'AZN.L', name: 'AstraZeneca', market: 'UK', sector: 'Healthcare', trading212: true },
  { ticker: 'HSBA.L', name: 'HSBC', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'ULVR.L', name: 'Unilever', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'BP.L', name: 'BP', market: 'UK', sector: 'Energy', trading212: true },
  { ticker: 'GSK.L', name: 'GSK', market: 'UK', sector: 'Healthcare', trading212: true },
  { ticker: 'RIO.L', name: 'Rio Tinto', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'LSEG.L', name: 'London Stock Exchange', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'DGE.L', name: 'Diageo', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'REL.L', name: 'RELX', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'BATS.L', name: 'BAT', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'NG.L', name: 'National Grid', market: 'UK', sector: 'Utilities', trading212: true },
  { ticker: 'VOD.L', name: 'Vodafone', market: 'UK', sector: 'Communication', trading212: true },
  { ticker: 'LLOY.L', name: 'Lloyds Banking', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'BARC.L', name: 'Barclays', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'NWG.L', name: 'NatWest', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'STAN.L', name: 'Standard Chartered', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'RKT.L', name: 'Reckitt Benckiser', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'CRH.L', name: 'CRH', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'EXPN.L', name: 'Experian', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'III.L', name: '3i Group', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'CPG.L', name: 'Compass Group', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'AAL.L', name: 'Anglo American', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'BKG.L', name: 'Berkeley Group', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'AHT.L', name: 'Ashtead Group', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'SMT.L', name: 'Scottish Mortgage', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'GLEN.L', name: 'Glencore', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'RR.L', name: 'Rolls-Royce', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'BA.L', name: 'BAE Systems', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'TSCO.L', name: 'Tesco', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'SBRY.L', name: 'Sainsbury', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'ABF.L', name: 'Associated British Foods', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'SGE.L', name: 'Sage Group', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'AUTO.L', name: 'Auto Trader', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'WISE.L', name: 'Wise', market: 'UK', sector: 'Fintech', trading212: true },
  { ticker: 'PRU.L', name: 'Prudential', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'LGEN.L', name: 'Legal & General', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'IHG.L', name: 'InterContinental Hotels', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'WTB.L', name: 'Whitbread', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  // FTSE 250
  { ticker: 'JET2.L', name: 'Jet2', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'FOUR.L', name: '4imprint', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'GAW.L', name: 'Games Workshop', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'WIZZ.L', name: 'Wizz Air', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'FRAS.L', name: 'Frasers Group', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'BME.L', name: 'B&M European', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'PSN.L', name: 'Persimmon', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'TW.L', name: 'Taylor Wimpey', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'BWY.L', name: 'Bellway', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  // AIM
  { ticker: 'FDEV.L', name: 'Frontier Developments', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'FEVR.L', name: 'Fevertree', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'JTC.L', name: 'JTC', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'GYM.L', name: 'Gym Group', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'CBG.L', name: 'Close Brothers', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'ENOG.L', name: 'Energean', market: 'UK', sector: 'Energy', trading212: true },
  { ticker: 'HBR.L', name: 'Harbour Energy', market: 'UK', sector: 'Energy', trading212: true },
  { ticker: 'ITM.L', name: 'ITM Power', market: 'UK', sector: 'Industrials', trading212: true },
  // Additional FTSE
  { ticker: 'MNDI.L', name: 'Mondi', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'ANTO.L', name: 'Antofagasta', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'PHNX.L', name: 'Phoenix Group', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'SPX.L', name: 'Spirax-Sarco', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'SMIN.L', name: 'Smiths Group', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'IAG.L', name: 'IAG', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'EZJ.L', name: 'easyJet', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'SSE.L', name: 'SSE', market: 'UK', sector: 'Utilities', trading212: true },
  { ticker: 'CNA.L', name: 'Centrica', market: 'UK', sector: 'Utilities', trading212: true },
  { ticker: 'SVT.L', name: 'Severn Trent', market: 'UK', sector: 'Utilities', trading212: true },
  { ticker: 'UU.L', name: 'United Utilities', market: 'UK', sector: 'Utilities', trading212: true },
  { ticker: 'OCDO.L', name: 'Ocado', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'LAND.L', name: 'Land Securities', market: 'UK', sector: 'Real Estate', trading212: true },
  { ticker: 'BLND.L', name: 'British Land', market: 'UK', sector: 'Real Estate', trading212: true },
  { ticker: 'SGRO.L', name: 'Segro', market: 'UK', sector: 'Real Estate', trading212: true },
  { ticker: 'BRBY.L', name: 'Burberry', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'JMAT.L', name: 'Johnson Matthey', market: 'UK', sector: 'Materials', trading212: true },
  // ── FTSE 100 (missing) ──
  { ticker: 'HLN.L', name: 'Haleon', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'NXT.L', name: 'Next', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'MKS.L', name: 'Marks & Spencer', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'WPP.L', name: 'WPP', market: 'UK', sector: 'Communication', trading212: true },
  { ticker: 'IMB.L', name: 'Imperial Brands', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'AV.L', name: 'Aviva', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'HLMA.L', name: 'Halma', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'HIK.L', name: 'Hikma Pharmaceuticals', market: 'UK', sector: 'Healthcare', trading212: true },
  { ticker: 'INF.L', name: 'Informa', market: 'UK', sector: 'Communication', trading212: true },
  { ticker: 'JD.L', name: 'JD Sports Fashion', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'KGF.L', name: 'Kingfisher', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'MRO.L', name: 'Melrose Industries', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'MNG.L', name: 'M&G', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'PSON.L', name: 'Pearson', market: 'UK', sector: 'Communication', trading212: true },
  { ticker: 'RTO.L', name: 'Rentokil Initial', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'RMV.L', name: 'Rightmove', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'SDR.L', name: 'Schroders', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'SN.L', name: 'Smith & Nephew', market: 'UK', sector: 'Healthcare', trading212: true },
  { ticker: 'WEIR.L', name: 'Weir Group', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'BNZL.L', name: 'Bunzl', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'CRDA.L', name: 'Croda International', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'ENT.L', name: 'Entain', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'FRES.L', name: 'Fresnillo', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'ADM.L', name: 'Admiral Group', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'BEZ.L', name: 'Beazley', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'DPLM.L', name: 'Diploma', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'EDV.L', name: 'Endeavour Mining', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'ITRK.L', name: 'Intertek Group', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'IMI.L', name: 'IMI', market: 'UK', sector: 'Industrials', trading212: true },
  // ── FTSE 250 (notable missing) ──
  { ticker: 'AJB.L', name: 'AJ Bell', market: 'UK', sector: 'Fintech', trading212: true },
  { ticker: 'AML.L', name: 'Aston Martin', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'GRG.L', name: 'Greggs', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'ITV.L', name: 'ITV', market: 'UK', sector: 'Communication', trading212: true },
  { ticker: 'DOM.L', name: "Domino's Pizza Group", market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'IGG.L', name: 'IG Group', market: 'UK', sector: 'Fintech', trading212: true },
  { ticker: 'DOCS.L', name: 'Dr. Martens', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'SCT.L', name: 'Softcat', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'BYIT.L', name: 'Bytes Technology', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'KNOS.L', name: 'Kainos Group', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'TRN.L', name: 'Trainline', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'DNLM.L', name: 'Dunelm', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'WOSG.L', name: 'Watches of Switzerland', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'CURY.L', name: 'Currys', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'DRX.L', name: 'Drax Group', market: 'UK', sector: 'Utilities', trading212: true },
  { ticker: 'PNN.L', name: 'Pennon Group', market: 'UK', sector: 'Utilities', trading212: true },
  { ticker: 'ONT.L', name: 'Oxford Nanopore', market: 'UK', sector: 'Healthcare', trading212: true },
  { ticker: 'RPI.L', name: 'Raspberry Pi', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'PLUS.L', name: 'Plus500', market: 'UK', sector: 'Fintech', trading212: true },
  { ticker: 'CERES.L', name: 'Ceres Power', market: 'UK', sector: 'Energy', trading212: true },
  { ticker: 'TATE.L', name: 'Tate & Lyle', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'VTY.L', name: 'Vistry Group', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'BBY.L', name: 'Balfour Beatty', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'QQ.L', name: 'QinetiQ', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'BAB.L', name: 'Babcock International', market: 'UK', sector: 'Industrials', trading212: true },
];

export const ALL_STOCKS: StockMeta[] = [...US_STOCKS, ...UK_STOCKS];
