export interface StockMeta {
  ticker: string;
  name: string;
  market: 'US' | 'UK';
  sector: string;
  trading212: boolean;
}

export const US_STOCKS: StockMeta[] = [
  // Tech - Mega Cap
  { ticker: 'AAPL', name: 'Apple', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'MSFT', name: 'Microsoft', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'GOOGL', name: 'Alphabet', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'AMZN', name: 'Amazon', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'NVDA', name: 'NVIDIA', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'META', name: 'Meta Platforms', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'TSLA', name: 'Tesla', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'AVGO', name: 'Broadcom', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'ORCL', name: 'Oracle', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'CRM', name: 'Salesforce', market: 'US', sector: 'Technology', trading212: true },
  // Tech - Growth
  { ticker: 'AMD', name: 'AMD', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'INTC', name: 'Intel', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'NFLX', name: 'Netflix', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'ADBE', name: 'Adobe', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'CSCO', name: 'Cisco', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'QCOM', name: 'Qualcomm', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'INTU', name: 'Intuit', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'AMAT', name: 'Applied Materials', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'PANW', name: 'Palo Alto Networks', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'SNPS', name: 'Synopsys', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'NOW', name: 'ServiceNow', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'UBER', name: 'Uber', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'SQ', name: 'Block', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'SHOP', name: 'Shopify', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'SNOW', name: 'Snowflake', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'PLTR', name: 'Palantir', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'NET', name: 'Cloudflare', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'CRWD', name: 'CrowdStrike', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'DDOG', name: 'Datadog', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'MDB', name: 'MongoDB', market: 'US', sector: 'Technology', trading212: true },
  // Financials
  { ticker: 'JPM', name: 'JPMorgan Chase', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'BAC', name: 'Bank of America', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'WFC', name: 'Wells Fargo', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'GS', name: 'Goldman Sachs', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'MS', name: 'Morgan Stanley', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'V', name: 'Visa', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'MA', name: 'Mastercard', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'AXP', name: 'American Express', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'BLK', name: 'BlackRock', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'SCHW', name: 'Charles Schwab', market: 'US', sector: 'Financials', trading212: true },
  // Healthcare
  { ticker: 'JNJ', name: 'Johnson & Johnson', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'UNH', name: 'UnitedHealth', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'PFE', name: 'Pfizer', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'ABBV', name: 'AbbVie', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'MRK', name: 'Merck', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'LLY', name: 'Eli Lilly', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'TMO', name: 'Thermo Fisher', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'ABT', name: 'Abbott Labs', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'AMGN', name: 'Amgen', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'GILD', name: 'Gilead Sciences', market: 'US', sector: 'Healthcare', trading212: true },
  // Consumer
  { ticker: 'WMT', name: 'Walmart', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'PG', name: 'Procter & Gamble', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'KO', name: 'Coca-Cola', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'PEP', name: 'PepsiCo', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'COST', name: 'Costco', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'MCD', name: "McDonald's", market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'NKE', name: 'Nike', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'SBUX', name: 'Starbucks', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'HD', name: 'Home Depot', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'LOW', name: "Lowe's", market: 'US', sector: 'Consumer Cyclical', trading212: true },
  // Energy
  { ticker: 'XOM', name: 'ExxonMobil', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'CVX', name: 'Chevron', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'COP', name: 'ConocoPhillips', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'SLB', name: 'Schlumberger', market: 'US', sector: 'Energy', trading212: true },
  { ticker: 'EOG', name: 'EOG Resources', market: 'US', sector: 'Energy', trading212: true },
  // Industrials
  { ticker: 'CAT', name: 'Caterpillar', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'BA', name: 'Boeing', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'HON', name: 'Honeywell', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'UPS', name: 'UPS', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'RTX', name: 'RTX Corp', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'DE', name: 'Deere & Co', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'GE', name: 'GE Aerospace', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'LMT', name: 'Lockheed Martin', market: 'US', sector: 'Industrials', trading212: true },
  // Communication
  { ticker: 'DIS', name: 'Disney', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'CMCSA', name: 'Comcast', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'T', name: 'AT&T', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'VZ', name: 'Verizon', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'TMUS', name: 'T-Mobile', market: 'US', sector: 'Communication', trading212: true },
  // Real Estate / Utilities
  { ticker: 'AMT', name: 'American Tower', market: 'US', sector: 'Real Estate', trading212: true },
  { ticker: 'PLD', name: 'Prologis', market: 'US', sector: 'Real Estate', trading212: true },
  { ticker: 'NEE', name: 'NextEra Energy', market: 'US', sector: 'Utilities', trading212: true },
  { ticker: 'DUK', name: 'Duke Energy', market: 'US', sector: 'Utilities', trading212: true },
  // Russell 2000 / Small-Mid growth
  { ticker: 'SOFI', name: 'SoFi Technologies', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'RIVN', name: 'Rivian', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'LCID', name: 'Lucid Group', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'COIN', name: 'Coinbase', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'RBLX', name: 'Roblox', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'U', name: 'Unity Software', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'AFRM', name: 'Affirm', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'HOOD', name: 'Robinhood', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'PATH', name: 'UiPath', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'PINS', name: 'Pinterest', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'SNAP', name: 'Snap', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'TTD', name: 'Trade Desk', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'ROKU', name: 'Roku', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'ZS', name: 'Zscaler', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'BILL', name: 'Bill Holdings', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'HUBS', name: 'HubSpot', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'SMCI', name: 'Super Micro', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'ARM', name: 'Arm Holdings', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'AI', name: 'C3.ai', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'CELH', name: 'Celsius Holdings', market: 'US', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'MARA', name: 'Marathon Digital', market: 'US', sector: 'Fintech', trading212: true },
  // Materials
  { ticker: 'LIN', name: 'Linde', market: 'US', sector: 'Materials', trading212: true },
  { ticker: 'APD', name: 'Air Products', market: 'US', sector: 'Materials', trading212: true },
  { ticker: 'FCX', name: 'Freeport-McMoRan', market: 'US', sector: 'Materials', trading212: true },
  { ticker: 'NEM', name: 'Newmont', market: 'US', sector: 'Materials', trading212: true },
  // Biotech
  { ticker: 'MRNA', name: 'Moderna', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'REGN', name: 'Regeneron', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'VRTX', name: 'Vertex Pharma', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'ISRG', name: 'Intuitive Surgical', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'DXCM', name: 'DexCom', market: 'US', sector: 'Healthcare', trading212: true },
  // More S&P 500
  { ticker: 'BRK-B', name: 'Berkshire Hathaway', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'SPGI', name: 'S&P Global', market: 'US', sector: 'Financials', trading212: true },
  { ticker: 'MMM', name: '3M', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'IBM', name: 'IBM', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'GEV', name: 'GE Vernova', market: 'US', sector: 'Industrials', trading212: true },
  { ticker: 'ABNB', name: 'Airbnb', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'GM', name: 'General Motors', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'F', name: 'Ford Motor', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'PYPL', name: 'PayPal', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'BKNG', name: 'Booking Holdings', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'TXN', name: 'Texas Instruments', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'MU', name: 'Micron', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'LRCX', name: 'Lam Research', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'KLAC', name: 'KLA Corp', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'ADI', name: 'Analog Devices', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'MRVL', name: 'Marvell Technology', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'ON', name: 'ON Semiconductor', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'FTNT', name: 'Fortinet', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'WDAY', name: 'Workday', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'TEAM', name: 'Atlassian', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'VEEV', name: 'Veeva Systems', market: 'US', sector: 'Healthcare', trading212: true },
  { ticker: 'ZM', name: 'Zoom Video', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'OKTA', name: 'Okta', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'DASH', name: 'DoorDash', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'SPOT', name: 'Spotify', market: 'US', sector: 'Communication', trading212: true },
  { ticker: 'SE', name: 'Sea Limited', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'MELI', name: 'MercadoLibre', market: 'US', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'NU', name: 'Nu Holdings', market: 'US', sector: 'Fintech', trading212: true },
  { ticker: 'GRAB', name: 'Grab Holdings', market: 'US', sector: 'Technology', trading212: true },
  { ticker: 'CPNG', name: 'Coupang', market: 'US', sector: 'Consumer Cyclical', trading212: true },
];

export const UK_STOCKS: StockMeta[] = [
  // FTSE 100
  { ticker: 'SHEL.L', name: 'Shell', market: 'UK', sector: 'Energy', trading212: true },
  { ticker: 'AZN.L', name: 'AstraZeneca', market: 'UK', sector: 'Healthcare', trading212: true },
  { ticker: 'HSBA.L', name: 'HSBC', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'ULVR.L', name: 'Unilever', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'BP.L', name: 'BP', market: 'UK', sector: 'Energy', trading212: true },
  { ticker: 'GSK.L', name: 'GSK', market: 'UK', sector: 'Healthcare', trading212: true },
  { ticker: 'RIO.L', name: 'Rio Tinto', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'LSEG.L', name: 'London Stock Exchange', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'DGE.L', name: 'Diageo', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'REL.L', name: 'RELX', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'BATS.L', name: 'BAT', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'NG.L', name: 'National Grid', market: 'UK', sector: 'Utilities', trading212: true },
  { ticker: 'VOD.L', name: 'Vodafone', market: 'UK', sector: 'Communication', trading212: true },
  { ticker: 'LLOY.L', name: 'Lloyds Banking', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'BARC.L', name: 'Barclays', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'NWG.L', name: 'NatWest', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'STAN.L', name: 'Standard Chartered', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'RKT.L', name: 'Reckitt Benckiser', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'CRH.L', name: 'CRH', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'EXPN.L', name: 'Experian', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'III.L', name: '3i Group', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'CPG.L', name: 'Compass Group', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'AAL.L', name: 'Anglo American', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'BKG.L', name: 'Berkeley Group', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'AHT.L', name: 'Ashtead Group', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'SMT.L', name: 'Scottish Mortgage', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'GLEN.L', name: 'Glencore', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'RR.L', name: 'Rolls-Royce', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'BA.L', name: 'BAE Systems', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'TSCO.L', name: 'Tesco', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'SBRY.L', name: 'Sainsbury', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'ABF.L', name: 'Associated British Foods', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'SGE.L', name: 'Sage Group', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'AUTO.L', name: 'Auto Trader', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'DARK.L', name: 'Darktrace', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'WISE.L', name: 'Wise', market: 'UK', sector: 'Fintech', trading212: true },
  { ticker: 'PRU.L', name: 'Prudential', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'LGEN.L', name: 'Legal & General', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'AVST.L', name: 'Avast', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'IHG.L', name: 'InterContinental Hotels', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'WTB.L', name: 'Whitbread', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  // FTSE 250
  { ticker: 'JET2.L', name: 'Jet2', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'FOUR.L', name: '4imprint', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'CINE.L', name: 'Cineworld', market: 'UK', sector: 'Communication', trading212: false },
  { ticker: 'GAW.L', name: 'Games Workshop', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'WIZZ.L', name: 'Wizz Air', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'FRAS.L', name: 'Frasers Group', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'BME.L', name: 'B&M European', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'PSN.L', name: 'Persimmon', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'TW.L', name: 'Taylor Wimpey', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'BWY.L', name: 'Bellway', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  // AIM
  { ticker: 'FDEV.L', name: 'Frontier Developments', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'KWS.L', name: 'Keywords Studios', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'BOO.L', name: 'boohoo', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'FEVR.L', name: 'Fevertree', market: 'UK', sector: 'Consumer Defensive', trading212: true },
  { ticker: 'JTC.L', name: 'JTC', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'GYM.L', name: 'Gym Group', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'CBG.L', name: 'Close Brothers', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'ENOG.L', name: 'Energean', market: 'UK', sector: 'Energy', trading212: true },
  { ticker: 'HBR.L', name: 'Harbour Energy', market: 'UK', sector: 'Energy', trading212: true },
  { ticker: 'ITM.L', name: 'ITM Power', market: 'UK', sector: 'Industrials', trading212: true },
  // Additional FTSE
  { ticker: 'MNDI.L', name: 'Mondi', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'ANTO.L', name: 'Antofagasta', market: 'UK', sector: 'Materials', trading212: true },
  { ticker: 'EVR.L', name: 'Evraz', market: 'UK', sector: 'Materials', trading212: false },
  { ticker: 'PHNX.L', name: 'Phoenix Group', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'HL.L', name: 'Hargreaves Lansdown', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'SPX.L', name: 'Spirax-Sarco', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'SMIN.L', name: 'Smiths Group', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'IAG.L', name: 'IAG', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'EZJ.L', name: 'easyJet', market: 'UK', sector: 'Industrials', trading212: true },
  { ticker: 'SSE.L', name: 'SSE', market: 'UK', sector: 'Utilities', trading212: true },
  { ticker: 'CNA.L', name: 'Centrica', market: 'UK', sector: 'Utilities', trading212: true },
  { ticker: 'SVT.L', name: 'Severn Trent', market: 'UK', sector: 'Utilities', trading212: true },
  { ticker: 'UU.L', name: 'United Utilities', market: 'UK', sector: 'Utilities', trading212: true },
  { ticker: 'OCDO.L', name: 'Ocado', market: 'UK', sector: 'Technology', trading212: true },
  { ticker: 'SGP.L', name: 'St James Place', market: 'UK', sector: 'Financials', trading212: true },
  { ticker: 'LAND.L', name: 'Land Securities', market: 'UK', sector: 'Real Estate', trading212: true },
  { ticker: 'BLND.L', name: 'British Land', market: 'UK', sector: 'Real Estate', trading212: true },
  { ticker: 'SGRO.L', name: 'Segro', market: 'UK', sector: 'Real Estate', trading212: true },
  { ticker: 'BRBY.L', name: 'Burberry', market: 'UK', sector: 'Consumer Cyclical', trading212: true },
  { ticker: 'JMAT.L', name: 'Johnson Matthey', market: 'UK', sector: 'Materials', trading212: true },
];

export const ALL_STOCKS: StockMeta[] = [...US_STOCKS, ...UK_STOCKS];
